### ISSUE TITLE
what is the difference with another repository: "gameformer"

### ISSUE THREAD

**Issue by teddyluo** [MCZhi/GameFormer-Planner#1]
hi,  can you point out what is the difference between this repository and another one: 
      https://github.com/MCZhi/GameFormer
if the code is the same, why open two repositories?

**Comment by MCZhi** [comment]
Hi, thank you for your question. The model used in both repositories is essentially the same. However, in this repository, the code focuses on training and testing using the nuPlan dataset and includes a comprehensive planning framework designed for closed-loop planning tests. On the other hand, the "gameformer" repository focuses on the Waymo dataset and open-loop prediction and planning tests.

**Comment by teddyluo** [comment]
noted. many thanks for the answer. 
By the way, which data set would you consider to more suitable for studying the planning task? nuPlan or Waymo ?

**Comment by MCZhi** [comment]
nuPlan would be more suitable.
