### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by StephenGordan** [MCZhi/GameFormer-Planner#10]
I run the test in docker. Is it possible to save the visualization data as videos or images?

**Comment by MCZhi** [comment]
You can try to export the content in the `testing_log` folder to your local machine and use `nuBoard` to visualize the simulation data in that folder.

**Comment by StephenGordan** [comment]
![f3991cec-8cc4-4569-83b4-8101c908ce5f](https://github.com/MCZhi/GameFormer-Planner/assets/62494499/e478ae01-a309-4055-a3e5-ed9a6d816514)
![6a491d95-521c-48e0-a924-cff02680bb7f](https://github.com/MCZhi/GameFormer-Planner/assets/62494499/595de2dc-81b6-4996-8be8-20c7c4cf39de)
Thank you very much!
Why is there data only in the overview, and none in the simulation? It cannot be visualized.

**Comment by StephenGordan** [comment]
In the settings, load the scene to visualize the result. But can the visualization window be enlarged?

**Comment by StephenGordan** [comment]
How to download the visualization vedio?

**Comment by shuiyue1999** [comment]
I have the same question, how you solve it?
