### ISSUE TITLE
Weights file

### ISSUE THREAD

**Issue by HenryDykhne** [MCZhi/GameFormer-Planner#14]
Hello. 

My team is planning on benchmarking your planner on a modified version of the nuplan benchmark. Would it be possible to get any associated weights files that this planner requires, in order to alleviate any possible issues we might have in retraining your model and avoid accidentally misrepresenting the capabilities of your planner?

**Comment by MCZhi** [comment]
Hi, @HenryDykhne, thank you for your interest. Sorry, we are unable to provide the weights file. See #2. However, you are encouraged to use the same training set to train the model for fairness,
