### ISSUE TITLE
ego's relative speed, acceleration

### ISSUE THREAD

**Issue by ZhengYinan-AIR** [MCZhi/GameFormer-Planner#15]
Hi @MCZhi ! Great work! 
I'm curious why the relative speed and acceleration are not calculated for the ego trajectory during the data processing stage.
![20240320-202024](https://github.com/MCZhi/GameFormer-Planner/assets/83967999/91c3b18b-f8b4-4e71-bfa0-69764b70bb1d)

**Comment by MCZhi** [comment]
Hi, @ZhengYinan-AIR, thank you for your interest. This is because speed and acceleration data are measured in the ego vehicle's local coordinate system, so they are already relative quantities.

**Comment by ZhengYinan-AIR** [comment]
Thank you for your reply. According to my understanding, egocentric means that the coordinates of all moments are converted into the relative coordinates of the current moment, which is the ego pose. In nuplan, the ego vehicle speed and acceleration are relative quantities relative to their respective timestamps, not relative to the current moment. 

Therefore, perhaps it is necessary to convert to relative velocity and acceleration at the current moment? @MCZhi

**Comment by MCZhi** [comment]
@ZhengYinan-AIR, yes, that makes sense. It's probably more reasonable to convert the ego vehicle's historical velocities and accelerations relative to the current moment. You can modify that as you need.

**Comment by ZhengYinan-AIR** [comment]
Thanks, it may not have much impact if the velocity coordinates are not converted to ego-centric.
