### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by dgj123456** [MCZhi/GameFormer-Planner#17]
Hi,

I'm trying to get a representative sample of your model,When I run this program
python data_process.py \
--data_path nuplan/dataset/nuplan-v1.1/splits/mini \
--map_path nuplan/dataset/maps \
--save_path nuplan/processed_data
When it comes to Rendering histograms:
the websit http://localhost:5006/is always show loading
Any advice here would be appreciated.

**Comment by MCZhi** [comment]
Hi, this may caused by your browser (chrome for example). Can you try a different browser?

**Comment by MCZhi** [comment]
Hi @dgj123456, do other functions in the nuBoard, such as simulation visualization, work well?

**Comment by dgj123456** [comment]
no

**Comment by MCZhi** [comment]
Can you try using another browser to load the website?

**Comment by dgj123456** [comment]
I've tried [Microsoft Edge] and Firefox, could you recommend a browser?

**Comment by MCZhi** [comment]
I just realized that there shouldn't be a website (nuBoard) pop up if you are just doing data_process. This website (nuBoard) is used only for testing evaluation.

**Comment by dgj123456** [comment]
My mistake should be this step，python run_nuplan_test.py \
--experiment_name open_loop_boxes \
--data_path nuplan/dataset/nuplan-v1.1/splits/mini \
--map_path nuplan/dataset/maps \
--model_path training_log/your/model

**Comment by MCZhi** [comment]
Can you try directly launching the nuBoard from the command line?
`python nuplan-devkit/nuplan/planning/script/run_nuboard.py simulation_path=/your/path`
