### ISSUE TITLE
Trajectory coordinate transformation causes the trajectory to be unsmooth

### ISSUE THREAD

**Issue by suannairen** [MCZhi/GameFormer-Planner#18]
Hello, I found that when processing the past trajectory of the ego vehicle, after the global coordinates are converted into local coordinates, the trajectory will become very unsmooth, but the real trajectory in the future will be smooth after this transformation. I found that when converting the past and future global coordinates, using two different functions resulted in different results.
They are convert_absolute_to_relative_poses, convert_absolute_quantities_to_relative (there may be problems)
Since the trajectory of the agent vehicle is also processed using convert_absolute_quantities_to_relative, this trajectory is also not smooth.
Below is the code diagram and the visualization you provided, the non-smooth trajectory that exists
![13](https://github.com/MCZhi/GameFormer-Planner/assets/89651140/55b63219-4933-4af6-b33f-69d9e9c69754)
![image](https://github.com/MCZhi/GameFormer-Planner/assets/89651140/e7979a62-ff39-4536-9958-2cff2506bbbf)
![9833c9f300c7b99bafefc92b627ad397](https://github.com/MCZhi/GameFormer-Planner/assets/89651140/5e87c6dc-dd91-4af5-abf9-bf6eda06d5ab)
![0e2c3131a48862edd2959945c9aaa667](https://github.com/MCZhi/GameFormer-Planner/assets/89651140/bd247b1f-6e2a-438a-9f39-72b269aefe01)
![fb8fa958f54cad65e71f47693fa5130b](https://github.com/MCZhi/GameFormer-Planner/assets/89651140/bce12245-69da-42fb-bda8-a0e464dd0198)

How to solve this problem

**Comment by MCZhi** [comment]
See this [issue](https://github.com/MCZhi/DTPP/issues/9)
