### ISSUE TITLE
Time-consuming for closed-loop Evaluation

### ISSUE THREAD

**Issue by JuggerNau** [MCZhi/GameFormer-Planner#19]
Hi, I am trying your great work on nuplan dataset, but it seems really time-consuming to do the closed-loop evaluation (it takes about 1 minute for each senario, that means about 2 hours for each .db file , which is impossible to test on all validation set). If I made some mistakes?

**Comment by MCZhi** [comment]
Yes, it would normally take that amount of time (about 1 minute) to finish running a 15-second scenario. I would not suggest testing on all cases in the validation set but some representative examples.

**Comment by 942411526** [comment]
> Yes, it would normally take that amount of time (about 1 minute) to finish running a 15-second scenario. I would not suggest testing on all cases in the validation set but some representative examples.

The result in the paper is test with set the scenarios_per_type=10?
