### ISSUE TITLE
Question about Dataset

### ISSUE THREAD

**Issue by hz3014** [MCZhi/GameFormer-Planner#3]
Hi, Thank you for your impressive work. I am new to NuPlan and i noticed the dataset 1.1 is huge. 

I was wondering do we need to download all archives or part of the dataset would enable training process? eg. mini dataset?  I also wonder if we need sensor_blobs at all since they are raw sensor data?

**Comment by MCZhi** [comment]
Hi, @hz3014. You can download any part of the dataset to train the model (the mini dataset is fine but I think it is a little small), and we don't need sensor_blobs data.
