### ISSUE TITLE
Visualization problem

### ISSUE THREAD

**Issue by ChenjieWang** [MCZhi/GameFormer-Planner#5]
Hi, thank you for sharing the great work!

I trained the model with nuPlan Mini Split. How can I get visualizations like Closed-loop Planning (nuPlan) shown in https://mczhi.github.io/GameFormer/?

Bests.

**Comment by MCZhi** [comment]
Hi, @ChenjieWang. Thank you for your interest in our work. Once you've completed the test, you can easily access your results through nuBoard. This feature will automatically pop up, allowing you to view your test results and analyze your performance.

**Comment by ChenjieWang** [comment]
@MCZhi. Thanks for your reply, I have successfully obtained the visual result with your help.

**Comment by StephenGordan** [comment]
How to use nuboard, do I need to modify the code?
Why is there data only in the overview, and none in the simulation? It cannot be visualized.
![f3991cec-8cc4-4569-83b4-8101c908ce5f](https://github.com/MCZhi/GameFormer-Planner/assets/62494499/2334092b-1565-4b91-b444-0a933dae2951)
![6a491d95-521c-48e0-a924-cff02680bb7f](https://github.com/MCZhi/GameFormer-Planner/assets/62494499/0ade2473-6609-4c06-9602-69a75e789306)
