### ISSUE TITLE
question  about drive command

### ISSUE THREAD

**Issue by dswangabel** [MCZhi/GameFormer-Planner#6]
Hi, thank you for sharing the great work!

How does the "drive command" integrate into the current task?  ''drive command"means turn left、turn right or go ahead command.

Bests.

**Comment by MCZhi** [comment]
Hi @dswangabel, thank you for your interest. We don't need the "drive command" in our task because we already have a pre-planned route for the vehicle to follow. The simulator provides us with the necessary route information, including "turn left" or "go ahead" instructions. Therefore, you don't have to worry about giving any driving commands.

**Comment by dswangabel** [comment]
Thanks a lot !  If " pre-planned route " that you said is  the  'data['route_lanes']'  corresponding  in the project code?  And i also have some questions? (1)I visualize the data output, the output result of lane looks curved，so i add the maximum number of points per feature and  change the interpolation method, but It doesn't seem to make a significant difference.  (2)The processed data doesn't seem to match the 2.8 million data points mentioned in the paper, despite using the provided data processing script for the full NuPlan data.
![1](https://github.com/MCZhi/GameFormer-Planner/assets/123939640/1c43f044-b76e-4873-ba09-14fada637f10)

**Comment by MCZhi** [comment]
About the "pre-planned route", the data['route_lanes'] comes from the dataset but differs slightly from the route used in the planner. I added the "route_lanes" in the predictor to better predict the initial plan of the ego vehicle, but to ensure the planning performance, you'll need a more sophisticated path planner to generate the route or reference path.
About the curved lanes, I don't know the exact reason, and it seems from the dataset itself. But I don't think it should mess with the model's performance.
As for the amount of data, how many data points do you have? We didn't set any specific scenario types in the challenge and used all the data we could get. If you're looking for more data points, you could try removing the scenario type restriction.
