### ISSUE TITLE
about interaction loss

### ISSUE THREAD

**Issue by fshi2006** [MCZhi/GameFormer-Planner#8]
hello! In the paper, you mentioned using interaction loss to ensure security between level k and k-1. But it seems that this part is not included in the code, can I get the code of this part? Thx a lot!

**Comment by MCZhi** [comment]
Hi, @fshi2006. Please refer to the code in the main repo [GameFormer](https://github.com/MCZhi/GameFormer/blob/main/utils/open_loop_train_utils.py).

**Comment by fshi2006** [comment]
thx a lot! So why didn't add this loss in planner repo?

**Comment by fshi2006** [comment]
thx a lot! So why didn't use this loss in planner repo?

**Comment by MCZhi** [comment]
This is because adding the interaction loss would significantly slow the training. Given the large amount of data from the nuPlan dataset, we need to remove this loss to speed up the training and thus train on more data.
