### ISSUE TITLE
train erro

### ISSUE THREAD

**Issue by StephenGordan** [MCZhi/GameFormer-Planner#9]
Why does it get stuck during training without giving any error messages?
<img width="967" alt="屏幕截图 2023-11-24 142647" src="https://github.com/MCZhi/GameFormer-Planner/assets/62494499/626ecac4-9042-43a1-897f-b50d2ab93f0c">

**Comment by StephenGordan** [comment]
The same problem in gameformer Interaction Prediction，but training suscessully in fameformer Open-loop Planning .

**Comment by StephenGordan** [comment]
Something wrong with optimizer.step() or data ?

**Comment by MCZhi** [comment]
I am not sure what's the problem. My guess is that a deadlock occurs in the data loading phase, so I would like to suggest reducing the number of worker threads in the DataLoader.

**Comment by StephenGordan** [comment]
Although the above issue hasn't been resolved, I managed to complete the model training on another device using a Docker environment. One issue is that Docker can't visualize in real-time. Is it possible to save the visualization data as videos or images?

**Comment by MCZhi** [comment]
See #10.
